function [ out,s,i1,i2,i3,i4,i5,i6,q1,q2,q3,q4,q5,q6,phaseError ] = detectSixtyFourQAM_phaseCorrection( s,ampMax )
    
    % Gain the signal to a reference level
    s=s./ampMax;

    % Detect the maximum and minimum Q and I components and their positions
    iMax=1/sqrt(2);
    iMin=-iMax;
    qMax=iMax;
    qMin=-qMax;
    phase=zeros(length(s),1);
    amp=phase;
    for i=1:length(s)
        amp(i)=sqrt( real(s(i))^2+imag(s(i))^2 );
        phase(i)=angle(s(i));
    end
   
    % Find all symbols which are in the right upper corner and average them
    UR=0;
    UL=0;
    DR=0;
    DL=0;
    URiden=0;
    ULiden=0;
    DRiden=0;
    DLiden=0;
    countUR=0;
    countUL=0;
    countDR=0;
    countDL=0;
    for i=1:length(s)
       if (imag(s(i))>=6*qMax/7 && real(s(i))>=6*iMax/7)
           URiden=1;
           UR=UR+s(i);
           countUR=countUR+1;
       elseif (imag(s(i))>=6*qMax/7 && real(s(i))<=6*iMin/7)
           ULiden=1;
           UL=UL+s(i);
           countUL=countUL+1;
       elseif (imag(s(i))<=6*qMin/7 && real(s(i))<=6*iMin/7)
           DLiden=1;
           DL=DL+s(i);
           countDL=countDL+1;
       elseif (imag(s(i))<=6*qMin/7 && real(s(i))>=6*iMax/7)
           DRiden=1;
           DR=DR+s(i);
           countDR=countDR+1;
       end
    end
    
    phaseError=0;
    if (URiden==1 || ULiden==1 || DRiden==1 || DLiden==1)
         phaseError=((pi/4-angle(UR/countUR))+(3*pi/4-angle(UL/countUL))+...
             (-3*pi/4-angle(DL/countDL))+(-pi/4-angle(DR/countDR)))/...
             (URiden+ULiden+DRiden+DLiden);
    end
    
    
    % Estimate the error in phase by substracting the averaged phase from the upper right
    % corner symbol from the correct phase (pi/4)
    %correctPhase=pi/4;
    %phaseError=correctPhase-atan(qCompAv/iCompAv);
    
    % Correct the estimated phase error att all the symbols
    for i=1:length(s)
        s(i)=amp(i)*cos(phase(i)+phaseError)+1i*amp(i)*sin(phase(i)+phaseError);
    end
    
    i1=iMin*5.8/7;
    i2=iMin*3.9/7;
    i3=iMin*2/7;
    i4=iMax*2/7;
    i5=iMax*3.9/7;
    i6=iMax*5.8/7;

    q1=qMin*5.8/7;
    q2=qMin*3.9/7;
    q3=qMin*2/7;
    q4=qMax*2/7;
    q5=qMax*3.9/7;
    q6=qMax*5.8/7;
    
    pos=1;
    b=zeros(length(s)*6,1);
    for i=1:length(s)
        if ( real(s(i)) < i1)
            if ( imag(s(i)) < q1 )
                b(pos) = 1;
                b(pos+1)=1;
                b(pos+2)=0;
                b(pos+3)=0;
                b(pos+4)=0;
                b(pos+5)=0;
            elseif ( imag(s(i))>= q1 && imag(s(i)) < q2 )
                b(pos) = 1;
                b(pos+1)=1;
                b(pos+2)=0;
                b(pos+3)=0;
                b(pos+4)=0;
                b(pos+5)=1;
            elseif ( imag(s(i))>= q2 && imag(s(i)) < q3 )
                b(pos) = 1;
                b(pos+1)=1;
                b(pos+2)=0;
                b(pos+3)=1;
                b(pos+4)=0;
                b(pos+5)=1;
            elseif ( imag(s(i))>= q3 && imag(s(i)) < 0 )
                b(pos) = 1;
                b(pos+1)=1;
                b(pos+2)=0;
                b(pos+3)=1;
                b(pos+4)=0;
                b(pos+5)=0;
            elseif ( imag(s(i))>= 0 && imag(s(i)) < q4 )
                b(pos) = 1;
                b(pos+1)=0;
                b(pos+2)=0;
                b(pos+3)=1;
                b(pos+4)=0;
                b(pos+5)=0;
            elseif ( imag(s(i))>= q4 && imag(s(i)) < q5 )
                b(pos) = 1;
                b(pos+1)=0;
                b(pos+2)=0;
                b(pos+3)=1;
                b(pos+4)=0;
                b(pos+5)=1;
            elseif ( imag(s(i))>= q5 && imag(s(i)) < q6 )
                b(pos) = 1;
                b(pos+1)=0;
                b(pos+2)=0;
                b(pos+3)=0;
                b(pos+4)=0;
                b(pos+5)=1;
            elseif ( imag(s(i))>= q6 )
                b(pos) = 1;
                b(pos+1)=0;
                b(pos+2)=0;
                b(pos+3)=0;
                b(pos+4)=0;
                b(pos+5)=0;
            end
        elseif ( real(s(i))>=i1 && real(s(i)) < i2)
            if ( imag(s(i)) < q1 )
                b(pos) = 1;
                b(pos+1)=1;
                b(pos+2)=0;
                b(pos+3)=0;
                b(pos+4)=1;
                b(pos+5)=0;
            elseif ( imag(s(i))>= q1 && imag(s(i)) < q2 )
                b(pos) = 1;
                b(pos+1)=1;
                b(pos+2)=0;
                b(pos+3)=0;
                b(pos+4)=1;
                b(pos+5)=1;
            elseif ( imag(s(i))>= q2 && imag(s(i)) < q3 )
                b(pos) = 1;
                b(pos+1)=1;
                b(pos+2)=0;
                b(pos+3)=1;
                b(pos+4)=1;
                b(pos+5)=1;
            elseif ( imag(s(i))>= q3 && imag(s(i)) < 0 )
                b(pos) = 1;
                b(pos+1)=1;
                b(pos+2)=0;
                b(pos+3)=1;
                b(pos+4)=1;
                b(pos+5)=0;
            elseif ( imag(s(i))>= 0 && imag(s(i)) < q4 )
                b(pos) = 1;
                b(pos+1)=0;
                b(pos+2)=0;
                b(pos+3)=1;
                b(pos+4)=1;
                b(pos+5)=0;
            elseif ( imag(s(i))>= q4 && imag(s(i)) < q5 )
                b(pos) = 1;
                b(pos+1)=0;
                b(pos+2)=0;
                b(pos+3)=1;
                b(pos+4)=1;
                b(pos+5)=1;
            elseif ( imag(s(i))>= q5 && imag(s(i)) < q6 )
                b(pos) = 1;
                b(pos+1)=0;
                b(pos+2)=0;
                b(pos+3)=0;
                b(pos+4)=1;
                b(pos+5)=1;
            elseif ( imag(s(i))>= q6 )
                b(pos) = 1;
                b(pos+1)=0;
                b(pos+2)=0;
                b(pos+3)=0;
                b(pos+4)=1;
                b(pos+5)=0;
            end
        elseif ( real(s(i))>=i2 && real(s(i)) < i3)
            if ( imag(s(i)) < q1 )
                b(pos) = 1;
                b(pos+1)=1;
                b(pos+2)=1;
                b(pos+3)=0;
                b(pos+4)=1;
                b(pos+5)=0;
            elseif ( imag(s(i))>= q1 && imag(s(i)) < q2 )
                b(pos) = 1;
                b(pos+1)=1;
                b(pos+2)=1;
                b(pos+3)=0;
                b(pos+4)=1;
                b(pos+5)=1;
            elseif ( imag(s(i))>= q2 && imag(s(i)) < q3 )
                b(pos) = 1;
                b(pos+1)=1;
                b(pos+2)=1;
                b(pos+3)=1;
                b(pos+4)=1;
                b(pos+5)=1;
            elseif ( imag(s(i))>= q3 && imag(s(i)) < 0 )
                b(pos) = 1;
                b(pos+1)=1;
                b(pos+2)=1;
                b(pos+3)=1;
                b(pos+4)=1;
                b(pos+5)=0;
            elseif ( imag(s(i))>= 0 && imag(s(i)) < q4 )
                b(pos) = 1;
                b(pos+1)=0;
                b(pos+2)=1;
                b(pos+3)=1;
                b(pos+4)=1;
                b(pos+5)=0;
            elseif ( imag(s(i))>= q4 && imag(s(i)) < q5 )
                b(pos) = 1;
                b(pos+1)=0;
                b(pos+2)=1;
                b(pos+3)=1;
                b(pos+4)=1;
                b(pos+5)=1;
            elseif ( imag(s(i))>= q5 && imag(s(i)) < q6 )
                b(pos) = 1;
                b(pos+1)=0;
                b(pos+2)=1;
                b(pos+3)=0;
                b(pos+4)=1;
                b(pos+5)=1;
            elseif ( imag(s(i))>= q6 )
                b(pos) = 1;
                b(pos+1)=0;
                b(pos+2)=1;
                b(pos+3)=0;
                b(pos+4)=1;
                b(pos+5)=0;
            end
        elseif ( real(s(i))>=i3 && real(s(i)) < 0)
            if ( imag(s(i)) < q1 )
                b(pos) = 1;
                b(pos+1)=1;
                b(pos+2)=1;
                b(pos+3)=0;
                b(pos+4)=0;
                b(pos+5)=0;
            elseif ( imag(s(i))>= q1 && imag(s(i)) < q2 )
                b(pos) = 1;
                b(pos+1)=1;
                b(pos+2)=1;
                b(pos+3)=0;
                b(pos+4)=0;
                b(pos+5)=1;
            elseif ( imag(s(i))>= q2 && imag(s(i)) < q3 )
                b(pos) = 1;
                b(pos+1)=1;
                b(pos+2)=1;
                b(pos+3)=1;
                b(pos+4)=0;
                b(pos+5)=1;
            elseif ( imag(s(i))>= q3 && imag(s(i)) < 0 )
                b(pos) = 1;
                b(pos+1)=1;
                b(pos+2)=1;
                b(pos+3)=1;
                b(pos+4)=0;
                b(pos+5)=0;
            elseif ( imag(s(i))>= 0 && imag(s(i)) < q4 )
                b(pos) = 1;
                b(pos+1)=0;
                b(pos+2)=1;
                b(pos+3)=1;
                b(pos+4)=0;
                b(pos+5)=0;
            elseif ( imag(s(i))>= q4 && imag(s(i)) < q5 )
                b(pos) = 1;
                b(pos+1)=0;
                b(pos+2)=1;
                b(pos+3)=1;
                b(pos+4)=0;
                b(pos+5)=1;
            elseif ( imag(s(i))>= q5 && imag(s(i)) < q6 )
                b(pos) = 1;
                b(pos+1)=0;
                b(pos+2)=1;
                b(pos+3)=0;
                b(pos+4)=0;
                b(pos+5)=1;
            elseif ( imag(s(i))>= q6 )
                b(pos) = 1;
                b(pos+1)=0;
                b(pos+2)=1;
                b(pos+3)=0;
                b(pos+4)=0;
                b(pos+5)=0;
            end
        elseif ( real(s(i))>=0 && real(s(i)) < i4)
            if ( imag(s(i)) < q1 )
                b(pos) = 0;
                b(pos+1)=1;
                b(pos+2)=1;
                b(pos+3)=0;
                b(pos+4)=0;
                b(pos+5)=0;
            elseif ( imag(s(i))>= q1 && imag(s(i)) < q2 )
                b(pos) = 0;
                b(pos+1)=1;
                b(pos+2)=1;
                b(pos+3)=0;
                b(pos+4)=0;
                b(pos+5)=1;
            elseif ( imag(s(i))>= q2 && imag(s(i)) < q3 )
                b(pos) = 0;
                b(pos+1)=1;
                b(pos+2)=1;
                b(pos+3)=1;
                b(pos+4)=0;
                b(pos+5)=1;
            elseif ( imag(s(i))>= q3 && imag(s(i)) < 0 )
                b(pos) = 0;
                b(pos+1)=1;
                b(pos+2)=1;
                b(pos+3)=1;
                b(pos+4)=0;
                b(pos+5)=0;
            elseif ( imag(s(i))>= 0 && imag(s(i)) < q4 )
                b(pos) = 0;
                b(pos+1)=0;
                b(pos+2)=1;
                b(pos+3)=1;
                b(pos+4)=0;
                b(pos+5)=0;
            elseif ( imag(s(i))>= q4 && imag(s(i)) < q5 )
                b(pos) = 0;
                b(pos+1)=0;
                b(pos+2)=1;
                b(pos+3)=1;
                b(pos+4)=0;
                b(pos+5)=1;
            elseif ( imag(s(i))>= q5 && imag(s(i)) < q6 )
                b(pos) = 0;
                b(pos+1)=0;
                b(pos+2)=1;
                b(pos+3)=0;
                b(pos+4)=0;
                b(pos+5)=1;
            elseif ( imag(s(i))>= q6 )
                b(pos) = 0;
                b(pos+1)=0;
                b(pos+2)=1;
                b(pos+3)=0;
                b(pos+4)=0;
                b(pos+5)=0;
            end
        elseif ( real(s(i))>=i4 && real(s(i)) < i5)
            if ( imag(s(i)) < q1 )
                b(pos) = 0;
                b(pos+1)=1;
                b(pos+2)=1;
                b(pos+3)=0;
                b(pos+4)=1;
                b(pos+5)=0;
            elseif ( imag(s(i))>= q1 && imag(s(i)) < q2 )
                b(pos) = 0;
                b(pos+1)=1;
                b(pos+2)=1;
                b(pos+3)=0;
                b(pos+4)=1;
                b(pos+5)=1;
            elseif ( imag(s(i))>= q2 && imag(s(i)) < q3 )
                b(pos) = 0;
                b(pos+1)=1;
                b(pos+2)=1;
                b(pos+3)=1;
                b(pos+4)=1;
                b(pos+5)=1;
            elseif ( imag(s(i))>= q3 && imag(s(i)) < 0 )
                b(pos) = 0;
                b(pos+1)=1;
                b(pos+2)=1;
                b(pos+3)=1;
                b(pos+4)=1;
                b(pos+5)=0;
            elseif ( imag(s(i))>= 0 && imag(s(i)) < q4 )
                b(pos) = 0;
                b(pos+1)=0;
                b(pos+2)=1;
                b(pos+3)=1;
                b(pos+4)=1;
                b(pos+5)=0;
            elseif ( imag(s(i))>= q4 && imag(s(i)) < q5 )
                b(pos) = 0;
                b(pos+1)=0;
                b(pos+2)=1;
                b(pos+3)=1;
                b(pos+4)=1;
                b(pos+5)=1;
            elseif ( imag(s(i))>= q5 && imag(s(i)) < q6 )
                b(pos) = 0;
                b(pos+1)=0;
                b(pos+2)=1;
                b(pos+3)=0;
                b(pos+4)=1;
                b(pos+5)=1;
            elseif ( imag(s(i))>= q6 )
                b(pos) = 0;
                b(pos+1)=0;
                b(pos+2)=1;
                b(pos+3)=0;
                b(pos+4)=1;
                b(pos+5)=0;
            end
        elseif ( real(s(i))>=i5 && real(s(i)) < i6)
            if ( imag(s(i)) < q1 )
                b(pos) = 0;
                b(pos+1)=1;
                b(pos+2)=0;
                b(pos+3)=0;
                b(pos+4)=1;
                b(pos+5)=0;
            elseif ( imag(s(i))>= q1 && imag(s(i)) < q2 )
                b(pos) = 0;
                b(pos+1)=1;
                b(pos+2)=0;
                b(pos+3)=0;
                b(pos+4)=1;
                b(pos+5)=1;
            elseif ( imag(s(i))>= q2 && imag(s(i)) < q3 )
                b(pos) = 0;
                b(pos+1)=1;
                b(pos+2)=0;
                b(pos+3)=1;
                b(pos+4)=1;
                b(pos+5)=1;
            elseif ( imag(s(i))>= q3 && imag(s(i)) < 0 )
                b(pos) = 0;
                b(pos+1)=1;
                b(pos+2)=0;
                b(pos+3)=1;
                b(pos+4)=1;
                b(pos+5)=0;
            elseif ( imag(s(i))>= 0 && imag(s(i)) < q4 )
                b(pos) = 0;
                b(pos+1)=0;
                b(pos+2)=0;
                b(pos+3)=1;
                b(pos+4)=1;
                b(pos+5)=0;
            elseif ( imag(s(i))>= q4 && imag(s(i)) < q5 )
                b(pos) = 0;
                b(pos+1)=0;
                b(pos+2)=0;
                b(pos+3)=1;
                b(pos+4)=1;
                b(pos+5)=1;
            elseif ( imag(s(i))>= q5 && imag(s(i)) < q6 )
                b(pos) = 0;
                b(pos+1)=0;
                b(pos+2)=0;
                b(pos+3)=0;
                b(pos+4)=1;
                b(pos+5)=1;
            elseif ( imag(s(i))>= q6 )
                b(pos) = 0;
                b(pos+1)=0;
                b(pos+2)=0;
                b(pos+3)=0;
                b(pos+4)=1;
                b(pos+5)=0;
            end
        elseif ( real(s(i))>=i6)
            if ( imag(s(i)) < q1 )
                b(pos) = 0;
                b(pos+1)=1;
                b(pos+2)=0;
                b(pos+3)=0;
                b(pos+4)=0;
                b(pos+5)=0;
            elseif ( imag(s(i))>= q1 && imag(s(i)) < q2 )
                b(pos) = 0;
                b(pos+1)=1;
                b(pos+2)=0;
                b(pos+3)=0;
                b(pos+4)=0;
                b(pos+5)=1;
            elseif ( imag(s(i))>= q2 && imag(s(i)) < q3 )
                b(pos) = 0;
                b(pos+1)=1;
                b(pos+2)=0;
                b(pos+3)=1;
                b(pos+4)=0;
                b(pos+5)=1;
            elseif ( imag(s(i))>= q3 && imag(s(i)) < 0 )
                b(pos) = 0;
                b(pos+1)=1;
                b(pos+2)=0;
                b(pos+3)=1;
                b(pos+4)=0;
                b(pos+5)=0;
            elseif ( imag(s(i))>= 0 && imag(s(i)) < q4 )
                b(pos) = 0;
                b(pos+1)=0;
                b(pos+2)=0;
                b(pos+3)=1;
                b(pos+4)=0;
                b(pos+5)=0;
            elseif ( imag(s(i))>= q4 && imag(s(i)) < q5 )
                b(pos) = 0;
                b(pos+1)=0;
                b(pos+2)=0;
                b(pos+3)=1;
                b(pos+4)=0;
                b(pos+5)=1;
            elseif ( imag(s(i))>= q5 && imag(s(i)) < q6 )
                b(pos) = 0;
                b(pos+1)=0;
                b(pos+2)=0;
                b(pos+3)=0;
                b(pos+4)=0;
                b(pos+5)=1;
            elseif ( imag(s(i))>= q6 )
                b(pos) = 0;
                b(pos+1)=0;
                b(pos+2)=0;
                b(pos+3)=0;
                b(pos+4)=0;
                b(pos+5)=0;
            end
        end
        pos=pos+6;
    end
    out=b;

end

